### ISSUE TITLE
Network breaking lint

### ISSUE THREAD

**Issue by rafaeltp** [masc-ucsc/cmpe220fall16#5]
For some weird reason those were not showing up with the original top module. That's the list of errors when running make lint

%Error: rtl/net_2core2dr.v:262: Can't find definition of variable: c0_drtol2i_snoop_ack_retry
%Error: rtl/net_2core2dr.v:262: Can't find definition of variable: c0_drtol2it_snoop_ack_retry
%Error: rtl/net_2core2dr.v:262: Can't find definition of variable: c0_drtol2d_0_snoop_ack_retry
%Error: rtl/net_2core2dr.v:262: Can't find definition of variable: c0_drtol2dt_0_snoop_ack_retry
%Error: rtl/net_2core2dr.v:263: Can't find definition of variable: c0_drtol2i_pfreq_retry
%Error: rtl/net_2core2dr.v:263: Can't find definition of variable: c0_drtol2it_pfreq_retry
%Error: rtl/net_2core2dr.v:263: Can't find definition of variable: c0_drtol2d_0_pfreq_retry
%Error: rtl/net_2core2dr.v:263: Can't find definition of variable: c0_drtol2dt_0_pfreq_retry
%Error: rtl/net_2core2dr.v:267: Can't find definition of variable: c1_drtol2i_snoop_ack_retry
%Error: rtl/net_2core2dr.v:267: Can't find definition of variable: c1_drtol2it_snoop_ack_retry
%Error: rtl/net_2core2dr.v:267: Can't find definition of variable: c1_drtol2d_0_snoop_ack_retry
%Error: rtl/net_2core2dr.v:267: Can't find definition of variable: c1_drtol2dt_0_snoop_ack_retry
%Error: rtl/net_2core2dr.v:268: Can't find definition of variable: c1_drtol2i_pfreq_retry
%Error: rtl/net_2core2dr.v:268: Can't find definition of variable: c1_drtol2it_pfreq_retry
%Error: rtl/net_2core2dr.v:268: Can't find definition of variable: c1_drtol2d_0_pfreq_retry
%Error: rtl/net_2core2dr.v:268: Can't find definition of variable: c1_drtol2dt_0_pfreq_retry
%Error: rtl/net_2core2dr.v:295: Can't find definition of scope/variable: c0_l2itodr_dack
%Error: rtl/net_2core2dr.v:303: Can't find definition of scope/variable: c0_l2itodr_dack
%Error: rtl/net_2core2dr.v:337: Can't find definition of scope/variable: c0_l2ittodr_dack
%Error: rtl/net_2core2dr.v:379: Can't find definition of variable: c0_l2dt_0todr_pfreq_valid
%Error: rtl/net_2core2dr.v:407: Can't find definition of scope/variable: c1_l2itodr_dack
%Error: rtl/net_2core2dr.v:415: Can't find definition of scope/variable: c1_l2itodr_dack
%Error-ASSIGNIN: rtl/net_2core2dr.v:294: Assigning to input variable: dr0tol2_dack
%Error-ASSIGNIN: rtl/net_2core2dr.v:296: Assigning to input variable: dr1tol2_dack
%Error-ASSIGNIN: rtl/net_2core2dr.v:304: Assigning to input variable: l2todr0_pfreq
%Error-ASSIGNIN: rtl/net_2core2dr.v:306: Assigning to input variable: l2todr1_pfreq
%Error-ASSIGNIN: rtl/net_2core2dr.v:336: Assigning to input variable: dr0tol2_dack
%Error-ASSIGNIN: rtl/net_2core2dr.v:338: Assigning to input variable: dr1tol2_dack
%Error-ASSIGNIN: rtl/net_2core2dr.v:406: Assigning to input variable: dr0tol2_dack
%Error-ASSIGNIN: rtl/net_2core2dr.v:408: Assigning to input variable: dr1tol2_dack
%Error-ASSIGNIN: rtl/net_2core2dr.v:416: Assigning to input variable: l2todr0_pfreq
%Error-ASSIGNIN: rtl/net_2core2dr.v:418: Assigning to input variable: l2todr1_pfreq

**Comment by grant1994** [comment]
I suspected my module was not quite ready... I rolled back the changes to the network rtl for now. The build is still broken.

**Comment by rafaeltp** [comment]
Just as general advise for anyone, you can use ```ifdef 0``` around your code and commit it, this will prevent it from breaking, while allowing you to commit.

**Comment by rafaeltp** [comment]
This seems fine now, closing the issue
