### ISSUE TITLE
Questions about using fflop

### ISSUE THREAD

**Issue by yzhu29** [masc-ucsc/cmpe220fall16#7]
Hi,

I have a question about using fflop, any help is appreciated but I hope either Professor or Rafael @rafaeltp  can answer my question too.

My question can be explained in the following picture. There are three fflops, A, B and C. The control logic I intend to design is to make them work as a transaction like operation. A, B and C must all succeed or fail as a complete unit; it can never be only partially complete. For example, if A and B may go, but C can't go, then A, B and C must retry. Only if when A, B and C are all ready, they can go. So how can I achieve this? I know one solution is to package them into one bigger fflop, but in my design I also want B to be a part of another pipeline flow.

![image](https://cloud.githubusercontent.com/assets/19315167/20458124/5ee6eba6-ae50-11e6-9a89-67f9487fb0f6.png)

Thanks.
Best,
Yuxiong

**Comment by rafaeltp** [comment]
Just and the signals together. Something like:

```
assign common_valid = a_valid & b_valid & c_valid;
assign common_retry = common_valid & a_next_retry & b_next_retry & c_next_retry;

fflop a (
    //...
   .dinValid(common_valid),
   .dinRetry(common_retry),
    //...
    //...
);
//...
```

**Comment by yzhu29** [comment]
But here comes the problem: .dinRetry is an output, assigning common_retry and connecting common_retry  to .dinRetry is creating a multiple driver problem. Also, since .dinRetry is an output, we can't affect the internal operation of fflop a from the outside, so fflop a will only pass the retry up but won't really stop and retry.

**Comment by rafaeltp** [comment]
You're right, my bad

```
assign common_valid = a_valid & b_valid & c_valid;
assign common_retry = ~common_valid | a_next_retry | b_next_retry | c_next_retry;

fflop a (
    //...
   .dinValid(common_valid),
   .dinRetry(a_retry),
    //...
    //...
);
//...
```

The common retry propagates back to whatever is feeding a, b and c.

**Comment by yzhu29** [comment]
Thanks, Ratael. Is this what you mean? (See the diagram below)
![image](https://cloud.githubusercontent.com/assets/19315167/20458696/803e29a8-ae60-11e6-8de9-cd6600f50c9c.png)

**Comment by rafaeltp** [comment]
No, the common retry should be in the other side of that diagram.

**Comment by yzhu29** [comment]
So is it like this?
![image](https://cloud.githubusercontent.com/assets/19315167/20458929/958daea4-ae66-11e6-9c84-0cc5757d54eb.png)

**Comment by rafaeltp** [comment]
Almost, check the code I poster. You need to or the inverse of valid_common to generate common_retry.
This will create the transaction behavior you mentioned, ie, if any of a,b,c is not valid, you stall all of them.

**Comment by yzhu29** [comment]
Thanks, I see. One more question about Fluid pipeline, please see the figure below. Suppose this pipeline has three fflops, the adjacent fflops are connected by the yellow logic cloud. Yellow logic cloud 1 is in the testbench, I believe we need to respect the retry signal there. That means, we need to manually and explicitly check SAi, if it's 1 then we need to resend Ai and VAi. But do we need to do this in yellow cloud 2 and yellow cloud 3 too? In other words, do we need to explicitly check SBi too, so that if it's 1 then we need to resend Bi and VBi? Or by connecting the fflops correctly, the retry signals will be honored implicitly?

![image](https://cloud.githubusercontent.com/assets/19315167/20459026/3fcaf33e-ae69-11e6-8407-4e79fced5d47.png)

**Comment by rafaeltp** [comment]
You don't need to worry about any  of that. The whole point of fflops is that this is already taken into account. If you are just linearly connecting the blocks in a datapath (as your figure suggests) you can safely connect Vao to Vbi and Sao to Sbi. 

You only need to do anything about valids and retries in case you want a different behavior (as the one you described in the original question).

**Comment by yzhu29** [comment]
Awesome, thanks a lot.
